services:
  crafty:
    container_name: crafty_controller
    image: arcadiatechnology/crafty-4:latest
    restart: unless-stopped
    ports:
      - "8443:8443"   # Painel HTTPS
      - "8123:8123"   # Dynmap/Bluemap (se usar)
      - "25565:25565" # Porta padrão do Minecraft (necessária para LAN e Playit)
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./crafty_data:/crafty/app/config
      - ./backups:/crafty/backups
      - ./servers:/crafty/servers  # Onde ficam os arquivos do servidor
    networks:
      - minecraft_net

  playit:
    container_name: playit_agent
    image: ghcr.io/playit-cloud/playit-agent:0.16
    restart: unless-stopped
    environment:
      - SECRET_KEY=${PLAYIT_GG_SECRET_KEY}
    depends_on:
      - crafty
    volumes:
      - ./playit_data:/config
    network_mode: host

networks:
  minecraft_net:
    driver: bridge